# Generated by Django 6.0.5 on 2026-05-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('dangerous_apps', models.IntegerField(default=0)),
                ('medium_apps', models.IntegerField(default=0)),
                ('safe_apps', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
            ],
        ),
    ]
