# Generated by Django 6.0.5 on 2026-05-30 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('package_name', models.CharField(blank=True, max_length=200)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apks/')),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('medium', 'Medium Risk'), ('dangerous', 'Dangerous')], default='safe', max_length=20)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('total_permissions', models.IntegerField(default=0)),
                ('dangerous_permissions_count', models.IntegerField(default=0)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=200)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='apk_analysis.loanapp')),
            ],
        ),
    ]
